#!/bin/bash

build() {
  for binary in whereisip rsync sync; do
    add_binary "$binary"
  done
  add_runscript
}

help() {
  cat << HELPEOF
This hook enables flashing of the root filesystem from a remote server.
HELPEOF
}
